### ISSUE TITLE
Error when starting rest-hapi plugin: Cannot set property 'Promise' of undefined

### ISSUE THREAD

**Issue by klishevich** [JKHeadley/rest-hapi#108]
I tried for two hours to start rest-hapi demo project, but failed. Maybe I missed something. Would appreciate help. 
When `node api.js` get error:
```bash
TypeError: Cannot set property 'Promise' of undefined
    at module.exports (/Users/mike/projects/a_learn/rest-hapi_test/node_modules/rest-hapi/components/mongoose-init.js:11:20)
    at Object.register (/Users/mike/projects/a_learn/rest-hapi_test/node_modules/rest-hapi/rest-hapi.js:67:57)
    at internals.Server.register (/Users/mike/projects/a_learn/rest-hapi_test/node_modules/hapi/lib/server.js:427:35)
    at api (/Users/mike/projects/a_learn/rest-hapi_test/api.js:31:18)
    at Object.<anonymous> (/Users/mike/projects/a_learn/rest-hapi_test/api.js:41:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

My `package.json`
```javascript
{
  "name": "bp-hapi-react-redux",
  "version": "1.0.0",
  "description": "Hapi React Redux Boilerplate",
  "main": "src/server.js",
  "scripts": {
    "lint": "eslint . --ext .js",
    "lint-fix": "eslint . --ext .js --fix",
    "build-babel": "rimraf .build-babel/ && babel ./src --out-dir .build-babel/src/ --copy-files",
    "start-babel": "NODE_ENV=localhost APP_MOCKS=1 node ./.build-babel/src/server",
    "start": "NODE_ENV=localhost APP_MOCKS=1 nodemon --exec babel-node src/server"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/klishevich/bp-hapi-react-redux.git"
  },
  "author": "Michael Klishevich",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/klishevich/bp-hapi-react-redux/issues"
  },
  "homepage": "https://github.com/klishevich/bp-hapi-react-redux#readme",
  "dependencies": {
    "axios": "^0.18.0",
    "hapi": "^17.3.1",
    "jsonwebtoken": "^8.2.1",
    "mongoose": "^5.1.0",
    "nock": "^9.2.5"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.11.0",
    "nodemon": "^1.17.3",
    "rimraf": "^2.6.2"
  }
}
```

My `api.js`
```
'use strict';

let Hapi = require('hapi');
let mongoose = require('mongoose');
let restHapi = require('rest-hapi');

async function api(){

    const server = new Hapi.Server(restHapi.config.server.connection);

    const plugins = [
        {
            name: 'restHapi',
            version: '1.0.0',
            register: restHapi.register,
            options: {
                mongoose: mongoose
            }
        }
    ]

    await server.register(plugins);
    await server.start();
    console.log(`Server running at: ${server.info.uri}`); // eslint-disable-line
}

process.on('unhandledRejection', (err) => {
    console.error(err); // eslint-disable-line
    process.exit(1);
});

api();
```

P.S. Also tried with canonical example from docs it does not work as well.

**Comment by JKHeadley** [comment]
Hi @klishevich, the `package.json` and `api.js` files you posted don't match the `rest-hapi-demo` files. Are you sure you posted the right files (the `package.json` you posted doesn't have a dependency on `rest-hapi` for instance)? I tested the `rest-hapi-demo` project and it seems to be working fine.

**Comment by klishevich** [comment]
@JKHeadley sorry my bad, copy pasted wrong file. I updated `package.json` it the issue and this is the link for GitHub repo with my test project - https://github.com/klishevich/a_learn/tree/master/rest-hapi_test

**Comment by JKHeadley** [comment]
@klishevich rest-hapi v1.0.0 is now available with Hapi 17 support.

**Comment by klishevich** [comment]
@JKHeadley thanks!
