### ISSUE TITLE
Error: TypeError: Joi.objectId is not a function

### ISSUE THREAD

**Issue by prawee** [JKHeadley/rest-hapi#11]
after seed already. then create api.js file and running.

`TypeError: Joi.objectId is not a function
    at Schema.statics.routeOptions.extraEndpoints (/private/var/www/hapi-rest/models/user.model.js:107:28)
    at Object.generateRoutes (/private/var/www/hapi-rest/node_modules/rest-hapi/utilities/rest-helper-factory.js:93:13)
    at /private/var/www/hapi-rest/node_modules/rest-hapi/rest-hapi.js:92:36
    at process.nextTick (/private/var/www/hapi-rest/node_modules/hapi/node_modules/hoek/lib/index.js:854:22)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

**Comment by prawee** [comment]
fixed  via using   https://www.npmjs.com/package/joi-objectid
thank you
