### ISSUE TITLE
Sample unit test for model

### ISSUE THREAD

**Issue by 1change** [JKHeadley/rest-hapi#141]
**Is your feature request related to a problem? Please describe.**
I'm new to Hapi & mongoose and trying to setup unit test for some model I define with Jest, but having found no references on google how to do it properly, so running into some sort of trial and error to make it work.

**Describe the solution you'd like**
One sample unit test where you could run CRUD or call method in a model

**Describe alternatives you've considered**
`

const Mongoose = require('mongoose')
const RestHapi = require('rest-hapi')
const Config = require('../../config')
const restHapiConfig = Config.get('/restHapiConfig')

// process.env.NODE_ENV = 'development'
const path = require('path')

// we require the handlers directly, so we can test the "Lib" functions in isolation
const Manifest = require('../../config/manifest.conf');
const Glue = require('glue');

describe('unit tests - programs', () => {
  let models

  beforeAll(async (done) => {

    RestHapi.config = restHapiConfig
    RestHapi.config.absoluteModelPath = true
    RestHapi.config.modelPath = path.join(__dirname, '../../server/models')

    models = await RestHapi.generateModels(Mongoose)

    const composeOptions = {
      relativeTo: path.join(__dirname, '../../')
    }

    const manifest = Manifest.get('/')
    const server = await Glue.compose(manifest, composeOptions)

    await server.start()

    done()
  })

  it('should return a report body', async (done) => {

    const logger = RestHapi.getLogger('test').bind()
    const UserData = Mongoose.model('user_program')
    let userData = await RestHapi.list(UserData, {$limit: 1}, logger)
    let reportBody = await models.program.getEvaluationSummary(userData, logger)
    console.log(reportBody)
    expect(reportBody).toBeDefined();
    done()
  });

  afterAll((done) => {
    process.exit(0)
    done()
  });

});
`

**Additional context**
Above is my trial and it works but could have been better, I guess having a setup.js and not calling generateModels and server.start every time.

**Comment by 1change** [comment]
When I tried to setup a globalSetup (instead of BeforeAll). It caused an issue like below. It seems mongoose don't store the models in globalSetup

```
MissingSchemaError: Schema hasn't been registered for model "user_program".
Use mongoose.model(name, schema)

      39 | 
      40 |     const logger = RestHapi.getLogger('test').bind()
    > 41 |     const UserData = Mongoose.model('user_program')
      42 |     const Program = Mongoose.model('program')
      43 |     let userData = await RestHapi.list(UserData, {$limit: 1}, logger)
      44 |     let reportBody = await Program.getEvaluationSummary(userData, logger)
      
      at new MissingSchemaError (node_modules/mongoose/lib/error/missingSchema.js:20:11)
      at Mongoose.Object.<anonymous>.Mongoose.model (node_modules/mongoose/lib/index.js:336:13)
      at Object.it (test/unit/program.model.test.js:41:31)
```

**Comment by JKHeadley** [comment]
Hi @1change, sorry for the late response, life has been busy lately.

Glad you got a working example. For your 'globalSetup', are you trying to run an external setup script (like the `setup.js` you mentioned)? I believe after you register the rest-hapi plugin you need to pass the `Mongoose` instance back to your test script instead of using a separate `require('mongoose')`. So maybe something like

```
const setup = require('setup.js')

...

const Mongoose = await setup()

```

Also, for the code you posted, since you are using `beforeAll` it should not have to call `server.start` and `generateModels` every time, correct?

**Comment by 1change** [comment]
Hi @JKHeadley, thx for taking the time. Yes beforeAll won't call server every time but in every testspec, so having a globalSetup would help.

**Comment by sanzoghenzo** [comment]
I went through some trial & errors, too, and I think I came to a decent solution.
`require('mongoose')` returns a singleton, so if you call if after the server creation, you get the cached mongoose instance.
The following example doesn't start the server (only initializes it), since I was interested in testing some methods declared in Schema.static without calling API endpoints.
I also make sure to close mongoose connection in order to avoid the "Jest did not exit one second after the test run has completed." message.

```
'use strict'

describe('Sample Test Suite', () => {
  let server, mongoose, sampleCollection, createdIds

  beforeAll(async (done) => {
    const Glue = require('glue')
    const Manifest = require('../../config/manifest.conf')
    const composeOptions = { relativeTo: '../../' }
    const manifest = Manifest.get('/')
    server = await Glue.compose(manifest, composeOptions)
    // getting mongoose singleton
    mongoose = require('mongoose')
    sampleCollection = mongoose.model('sampleCollection')
    done()
  })

  beforeEach(async (done) => {
    // populate collections
    const sampleData = [...] 
    const newObjs = await sampleCollection.insertMany(pois)
    createdIds = newObjs.map(o => o._id)
    done()
  })

  test('sample test', async (done) => {
    // write you test here...
    done()
  })

  afterEach((done) => {
      if (createdIds.length) {
        sampleCollection.deleteMany({ _id: { $in: createdIds } })
      }
      done()
  })

  afterAll((done) => {
      mongoose.connection.close()
      done()
  })
})
```

[this](https://stackoverflow.com/a/25615947/4149512) can be useful too.

**Comment by JKHeadley** [comment]
@sanzoghenzo very nice! Yes getting things in the right order can be a bit tricky. Thanks for sharing your solution!

As a side note, if you find spinning up a MongoDB instance too slow or cumbersome, you can using [mongodb-memory-server](https://github.com/nodkz/mongodb-memory-server). See [this comment](https://github.com/JKHeadley/rest-hapi/issues/170#issuecomment-481324779).
