### ISSUE TITLE
error when mongodb uri with mongodb+srv

### ISSUE THREAD

**Issue by karabaralex** [JKHeadley/rest-hapi#168]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by karabaralex** [comment]
steps to repro:
1. create a mongodb cluster at Atlas
2. get connection uri which looks like 
mongodb+srv://<some>.mongodb.net/test?retryWrites=true
3. add this uri to rest-hapi config 
      mongo: {
        URI: 'mongodb+srv://<some>.mongodb.net/test?retryWrites=true',
      },
4. npm start

```
UnhandledPromiseRejectionWarning: Error: Invalid mongodb uri "mongodb+srv://<name>mongodb.net/test?retryWrites=true". Must begin with "mongodb://"
    at muri (/node_modules/muri/lib/index.js:28:11)
    at NativeConnection.Connection._handleOpenArgs (/node_modules/mongoose/lib/connection.js:199:16)
```
