### ISSUE TITLE
TypeError: Cannot read property 'schemaName' of undefined

### ISSUE THREAD

**Issue by duartealexf** [JKHeadley/rest-hapi#30]
Hi there. I keep running into this error when trying to startup my application. I've looked for help in Google, with no luck. Unfortunately i can't share much of the code, but here's the stacktrace:

```
[18:18:32.087] 47383 NOTE     api/layout/List — Generating List endpoint for layout
[18:18:32.093] 47383 ERROR    node_modules/rest-hapi/utilities/rest-helper-factory.js:98:16 api — Error: TypeError: Cannot read property 'schemaName' of undefined
[18:18:32.093] 47383 ERROR    node_modules/rest-hapi/utilities/rest-helper-factory.js:98:16 api —     at Object.generateJoiModelFromFieldType (/var/www/private/node_modules/rest-hapi/utilities/joi-mongoose-helper.js:213:27)
[18:18:32.093] 47383 ERROR    node_modules/rest-hapi/utilities/rest-helper-factory.js:98:16 api —     at /var/www/private/node_modules/rest-hapi/utilities/rest-helper-factory.js:169:46
[18:18:32.093] 47383 ERROR    node_modules/rest-hapi/utilities/rest-helper-factory.js:98:16 api —     at arrayEach (/var/www/private/node_modules/rest-hapi/node_modules/lodash/index.js:1289:13)
[18:18:32.093] 47383 ERROR    node_modules/rest-hapi/utilities/rest-helper-factory.js:98:16 api —     at Function.<anonymous> (/var/www/private/node_modules/rest-hapi/node_modules/lodash/index.js:3345:13)
[18:18:32.093] 47383 ERROR    node_modules/rest-hapi/utilities/rest-helper-factory.js:98:16 api —     at Object.generateListEndpoint (/var/www/private/node_modules/rest-hapi/utilities/rest-helper-factory.js:168:11)
[18:18:32.093] 47383 ERROR    node_modules/rest-hapi/utilities/rest-helper-factory.js:98:16 api —     at Object.generateRoutes (/var/www/private/node_modules/rest-hapi/utilities/rest-helper-factory.js:51:16)
[18:18:32.093] 47383 ERROR    node_modules/rest-hapi/utilities/rest-helper-factory.js:98:16 api —     at /var/www/private/node_modules/rest-hapi/rest-hapi.js:92:36
[18:18:32.093] 47383 ERROR    node_modules/rest-hapi/utilities/rest-helper-factory.js:98:16 api —     at process.nextTick (/var/www/private/node_modules/hapi/node_modules/hoek/lib/index.js:858:22)
[18:18:32.093] 47383 ERROR    node_modules/rest-hapi/utilities/rest-helper-factory.js:98:16 api —     at _combinedTickCallback (internal/process/next_tick.js:73:7)
[18:18:32.093] 47383 ERROR    node_modules/rest-hapi/utilities/rest-helper-factory.js:98:16 api —     at process._tickCallback (internal/process/next_tick.js:104:9)
```

Tell me if you need more details.
I'm using the latest version of rest-hapi.
Thanks.

**Comment by JKHeadley** [comment]
That error would occur if you are not assigning a type to one of your model properties. For example:

```javascript
module.exports = function (mongoose) {
  var modelName = "role";
  var Types = mongoose.Schema.Types;
  var Schema = new mongoose.Schema({
    name: {
      type: Types.String,                                                  //<-----type
      enum: ["Account", "Admin", "SuperAdmin"],
      required: true
    },
    enabled: {
      type: Types.Boolean                                               //<-----type
    }
  }, { collection: modelName });
    
  Schema.statics = {
    collectionName:modelName,
    routeOptions: {
    }
  };

  return Schema;
};
```

**Comment by duartealexf** [comment]
Thanks for the reply @JKHeadley, but actually I am setting the type. Might this error be because of my 'cols' empty array property? This is my model:
```
module.exports = function (mongoose) {
    var modelName = "layout";
    var Types = mongoose.Schema.Types;


    var schema = new mongoose.Schema({
        name: {
            type: Types.String,
            required: true
        },
        thumb: {
            type: Types.String
        },
        cols: []
    }, { collection: modelName });

...
```
I'm also setting some `schema.statics` after that, but I'm not sure it is related to the error.

Thanks again.

**Comment by JKHeadley** [comment]
yes, it is due to the empty `cols` array.  If you assign a type to the array, it should fix that, for example:

```
cols: [Type.String]
```
or even

```
cols: [{}]
```
should work.

**Comment by duartealexf** [comment]
Thanks @JKHeadley,
I used the first solution and it worked.

I also found another way to fix it:

```
cols: {
    type: Array,
    default: []
}
```
