### ISSUE TITLE
Allow, flexible object fields for models.

### ISSUE THREAD

**Issue by rahil471** [JKHeadley/rest-hapi#72]
I have a requirement, where I want to allow the users of my service to input any data into my model. Some metadata. 

I have tried using `Types.Mixed` and `Types.Object` to get past this, but when I make a request, rest-hapi says `key` is not allowed. 
I think this was working uptil v 0.20, I recently updated to 0.33. 

Thanks in advance.

**Comment by JKHeadley** [comment]
@rahil471 fixed this issue in v0.33.5

**Comment by rahil471** [comment]
I tested this in v0.34. This is the error I still get.

`"value\" at position 0 fails because [child \"user.user_metadataCreateModel\" fails because [\"currency\" is not allowed]], \"userCreateModel\" must be an object`

**Comment by rahil471** [comment]
This is my defined model. 

```
schema = {
.,
..,
...,
user_metadata: {
            type: Types.Mixed,
            required: false
        },
...,
..,
.
}
```

**Comment by rahil471** [comment]
@JKHeadley Should this be reopened?

**Comment by JKHeadley** [comment]
@rahil471 could you provide an example payload?

**Comment by rahil471** [comment]
Sure, 

Here is an example request. 

```
[
  {
    "firstName": "Rahil",
    "lastName": "Shaikh",
    "picture": "string",
    "username": "rahil",
    "password": "mysecret",
    "phone_number": 11111111111,
    "email": "rahil@temp.com",
    "user_metadata": {
       "extra": "test"
},
    "role": "5a02ca3026464d002393b26b"
  }
]
```

and this is the response. 

```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "\"value\" at position 0 fails because [child \"user.user_metadataCreateModel\" fails because [\"extra\" is not allowed]], \"userCreateModel\" must be an object",
  "validation": {
    "source": "payload",
    "keys": [
      "0.user_metadata.extra",
      "userCreateModel"
    ]
  }
}
```

**Comment by JKHeadley** [comment]
Thanks @rahil471 

I updated the bug fix.  Please try v0.34.3 to see if it works with your case.

**Comment by rahil471** [comment]
I think there is some problem with the new version. `rest-hapi` is not creating all the API's. 
As soon as res-hapi got upgraded to `0.34.3` a lot of my APIs started responding with 404 (even the swagger doc is not listing all API's), reverting the version back to `0.34.0` solved that thing, I'll still check again and confirm.

**Comment by JKHeadley** [comment]
@rahil471 we're there any errors when you started the server?

**Comment by rahil471** [comment]
Yes, there are errors but the app starts. 
Here is the stack trace. 

```
ERROR    node_modules\rest-hapi\utilities\rest-helper-factory.js:99:16 api — Error: TypeError: Cannot read property '0' of u
ndefined
    at Object.internals.generateJoiFieldModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:316:43)
    at internals.generateJoiReadModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:44:42)
    at Object.internals.generateJoiFieldModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:365:18)
    at internals.generateJoiReadModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:44:42)
    at Object.internals.generateJoiFieldModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:365:18)
    at Object.internals.generateJoiReadModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:44:42)
    at Object.generateListEndpoint (D:\Work\abp-users\node_modules\rest-hapi\utilities\rest-helper-factory.js:135:41)
    at Object.generateRoutes (D:\Work\abp-users\node_modules\rest-hapi\utilities\rest-helper-factory.js:52:16)
    at D:\Work\abp-users\node_modules\rest-hapi\rest-hapi.js:168:28
    at _fulfilled (D:\Work\abp-users\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (D:\Work\abp-users\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (D:\Work\abp-users\node_modules\q\q.js:816:13)
    at D:\Work\abp-users\node_modules\q\q.js:624:44
    at runSingle (D:\Work\abp-users\node_modules\q\q.js:137:13)
    at flush (D:\Work\abp-users\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
[17:06:16.309] 106396 ERROR    node_modules\rest-hapi\rest-hapi.js:177:20 api — TypeError: Cannot read property '0' of undefined
    at Object.internals.generateJoiFieldModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:316:43)
    at internals.generateJoiReadModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:44:42)
    at Object.internals.generateJoiFieldModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:365:18)
    at internals.generateJoiReadModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:44:42)
    at Object.internals.generateJoiFieldModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:365:18)
    at Object.internals.generateJoiReadModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:44:42)
    at Object.generateListEndpoint (D:\Work\abp-users\node_modules\rest-hapi\utilities\rest-helper-factory.js:135:41)
    at Object.generateRoutes (D:\Work\abp-users\node_modules\rest-hapi\utilities\rest-helper-factory.js:52:16)
    at D:\Work\abp-users\node_modules\rest-hapi\rest-hapi.js:168:28
    at _fulfilled (D:\Work\abp-users\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (D:\Work\abp-users\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (D:\Work\abp-users\node_modules\q\q.js:816:13)
    at D:\Work\abp-users\node_modules\q\q.js:624:44
    at runSingle (D:\Work\abp-users\node_modules\q\q.js:137:13)
    at flush (D:\Work\abp-users\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
Failed to load plugin: TypeError: Cannot read property '0' of undefined
    at Object.internals.generateJoiFieldModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:316:43)
    at internals.generateJoiReadModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:44:42)
    at Object.internals.generateJoiFieldModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:365:18)
    at internals.generateJoiReadModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:44:42)
    at Object.internals.generateJoiFieldModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:365:18)
    at Object.internals.generateJoiReadModel (D:\Work\abp-users\node_modules\rest-hapi\utilities\joi-mongoose-helper.js:44:42)
    at Object.generateListEndpoint (D:\Work\abp-users\node_modules\rest-hapi\utilities\rest-helper-factory.js:135:41)
    at Object.generateRoutes (D:\Work\abp-users\node_modules\rest-hapi\utilities\rest-helper-factory.js:52:16)
    at D:\Work\abp-users\node_modules\rest-hapi\rest-hapi.js:168:28
    at _fulfilled (D:\Work\abp-users\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (D:\Work\abp-users\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (D:\Work\abp-users\node_modules\q\q.js:816:13)
    at D:\Work\abp-users\node_modules\q\q.js:624:44
    at runSingle (D:\Work\abp-users\node_modules\q\q.js:137:13)
    at flush (D:\Work\abp-users\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
```

**Comment by JKHeadley** [comment]
@rahil471 Thanks for the help and your patience with this. I added an updated fix to v0.34.4. Please try it and see if it works for you.

**Comment by rahil471** [comment]
I can confirm that the bug introduced coz of the attempted fix is fixed, but the original issue of **unknown fields still remains**.

@JKHeadley  No mention, I really love this framework and would love to contribute to it. 
In fact, I have built an advanced user-management system on top of appy, with features like social-login, saml, ldap etc. I'll see if my employer allows me to make it open-source (I'll let you know), if not then I'll start recreating these features for appy as soon as I get some time if you say so.

**Comment by rahil471** [comment]
Hey @JKHeadley  my bad, I was checking in the wrong running instance.

The original bug of flexible/unknown object fields is fixed along with the bug introduced in the attempted fix.  

One very minor thing, in swagger docs the fields defined as Object are shown as strings under example value. 

Thanks for your prompt updates and efforts.

**Comment by JKHeadley** [comment]
@rahil471 glad to hear it!  Thanks for pointing out the swagger issue as well.  I pushed an update to fix that for v0.35.0.

Thanks for your support.  Any contributions to rest-hapi or appy are well appreciated.  I'm especially interested to see your implementation of saml and ldap.  I'm currently working on a web front end for appy so hopefully soon it will provide a fully functional web app.

**Comment by rahil471** [comment]
@JKHeadley Sounds great. Looking forward to contributing to it.

Are you planning to make the web front-end opensource as well?

**Comment by JKHeadley** [comment]
@rahil471 yes it will definitely be open source.  Looking forward to your contributions!
