### ISSUE TITLE
First time setup/Demo error

### ISSUE THREAD

**Issue by kpfromer** [JKHeadley/rest-hapi#74]
I am trying to start up a basic rest-hapi example using your example code, but I am encountering an error. When I launch `./node_modules/.bin/rest-hapi-cli seed` I get this error:
```
[21:10:20] Working directory changed to ~/WebstormProjects/deleteme/node_modules/rest-hapi

module.js:471
    throw err;
    ^

Error: Cannot find module '../tests/test-helper.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kpfromer/WebstormProjects/deleteme/node_modules/rest-hapi/gulp/test.js:6:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireDir (/Users/kpfromer/WebstormProjects/deleteme/node_modules/require-dir/index.js:123:33)
    at Object.<anonymous> (/Users/kpfromer/WebstormProjects/deleteme/node_modules/rest-hapi/gulpfile.js:9:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by JKHeadley** [comment]
@kpfromer fixed this bug in v0.34.1
